// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gwtplatform.samples.basic.server.domain;

import com.cristal.storm.prototype.server.domain.MCE;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect MCEDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MCEDataOnDemand: @Component;
    
    private Random MCEDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<MCE> MCEDataOnDemand.data;
    
    public MCE MCEDataOnDemand.getNewTransientMCE(int index) {
        com.cristal.storm.prototype.server.domain.MCE obj = new com.cristal.storm.prototype.server.domain.MCE();
        obj.setUri("uri_" + index);
        java.lang.String tag = "tag_" + index;
        if (tag.length() > 12) {
            tag  = tag.substring(0, 12);
        }
        obj.setTag(tag);
        obj.setCreated(new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime());
        return obj;
    }
    
    public MCE MCEDataOnDemand.getSpecificMCE(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        MCE obj = data.get(index);
        return MCE.findMCE(obj.getId());
    }
    
    public MCE MCEDataOnDemand.getRandomMCE() {
        init();
        MCE obj = data.get(rnd.nextInt(data.size()));
        return MCE.findMCE(obj.getId());
    }
    
    public boolean MCEDataOnDemand.modifyMCE(MCE obj) {
        return false;
    }
    
    public void MCEDataOnDemand.init() {
        data = com.cristal.storm.prototype.server.domain.MCE.findMCEEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'MCE' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.cristal.storm.prototype.server.domain.MCE>();
        for (int i = 0; i < 10; i++) {
            com.cristal.storm.prototype.server.domain.MCE obj = getNewTransientMCE(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
