// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gwtplatform.samples.basic.server.domain;

import com.gwtplatform.samples.basic.server.domain.MCEDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MCEIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MCEIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MCEIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: MCEIntegrationTest: @Transactional;
    
    @Autowired
    private MCEDataOnDemand MCEIntegrationTest.dod;
    
    @Test
    public void MCEIntegrationTest.testCountMCES() {
        org.junit.Assert.assertNotNull("Data on demand for 'MCE' failed to initialize correctly", dod.getRandomMCE());
        long count = com.cristal.storm.prototype.server.domain.MCE.countMCES();
        org.junit.Assert.assertTrue("Counter for 'MCE' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MCEIntegrationTest.testFindMCE() {
        com.cristal.storm.prototype.server.domain.MCE obj = dod.getRandomMCE();
        org.junit.Assert.assertNotNull("Data on demand for 'MCE' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MCE' failed to provide an identifier", id);
        obj = com.cristal.storm.prototype.server.domain.MCE.findMCE(id);
        org.junit.Assert.assertNotNull("Find method for 'MCE' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'MCE' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MCEIntegrationTest.testFindAllMCES() {
        org.junit.Assert.assertNotNull("Data on demand for 'MCE' failed to initialize correctly", dod.getRandomMCE());
        long count = com.cristal.storm.prototype.server.domain.MCE.countMCES();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'MCE', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.cristal.storm.prototype.server.domain.MCE> result = com.cristal.storm.prototype.server.domain.MCE.findAllMCES();
        org.junit.Assert.assertNotNull("Find all method for 'MCE' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'MCE' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MCEIntegrationTest.testFindMCEEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'MCE' failed to initialize correctly", dod.getRandomMCE());
        long count = com.cristal.storm.prototype.server.domain.MCE.countMCES();
        if (count > 20) count = 20;
        java.util.List<com.cristal.storm.prototype.server.domain.MCE> result = com.cristal.storm.prototype.server.domain.MCE.findMCEEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'MCE' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'MCE' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MCEIntegrationTest.testFlush() {
        com.cristal.storm.prototype.server.domain.MCE obj = dod.getRandomMCE();
        org.junit.Assert.assertNotNull("Data on demand for 'MCE' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MCE' failed to provide an identifier", id);
        obj = com.cristal.storm.prototype.server.domain.MCE.findMCE(id);
        org.junit.Assert.assertNotNull("Find method for 'MCE' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMCE(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'MCE' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MCEIntegrationTest.testMerge() {
        com.cristal.storm.prototype.server.domain.MCE obj = dod.getRandomMCE();
        org.junit.Assert.assertNotNull("Data on demand for 'MCE' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MCE' failed to provide an identifier", id);
        obj = com.cristal.storm.prototype.server.domain.MCE.findMCE(id);
        boolean modified =  dod.modifyMCE(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.cristal.storm.prototype.server.domain.MCE merged = (com.cristal.storm.prototype.server.domain.MCE) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'MCE' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MCEIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'MCE' failed to initialize correctly", dod.getRandomMCE());
        com.cristal.storm.prototype.server.domain.MCE obj = dod.getNewTransientMCE(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'MCE' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'MCE' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'MCE' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MCEIntegrationTest.testRemove() {
        com.cristal.storm.prototype.server.domain.MCE obj = dod.getRandomMCE();
        org.junit.Assert.assertNotNull("Data on demand for 'MCE' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MCE' failed to provide an identifier", id);
        obj = com.cristal.storm.prototype.server.domain.MCE.findMCE(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'MCE' with identifier '" + id + "'", com.cristal.storm.prototype.server.domain.MCE.findMCE(id));
    }
    
}
