// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gwtplatform.samples.basic.server.domain;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MCEIntegrationTest_Roo_Configurable {
    
    declare @type: MCEIntegrationTest: @Configurable;
    
}
