// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cristal.storm.prototype.server.domain;

import java.lang.String;

privileged aspect Tag_Roo_ToString {
    
    public String Tag.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Tag: ").append(getTag());
        return sb.toString();
    }
    
}
