// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cristal.storm.prototype.server.domain;

import java.lang.String;

privileged aspect Tag_Roo_JavaBean {
    
    public String Tag.getTag() {
        return this.tag;
    }
    
    public void Tag.setTag(String tag) {
        this.tag = tag;
    }
    
}
